name: Testes Integrados de API com Newman

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
  
env:
  MESSAGE: Resultado da última execução dos testes
  REPORT_JSON_PATH: report/result.json


jobs:
    
  comment-pr-newman:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Download a Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: report
          path: report
  
      - name: JSON to variables
        uses: rgarcia-phi/json-to-variables@v1.1.0
        if: github.event_name == 'pull_request'
        with:
          filename: ${{ env.REPORT_JSON_PATH }}
          prefix: result
          # masked: true

      - uses: mshick/add-pr-comment@v1
        if: github.event_name == 'pull_request'
        with:
          message: |
            ### 🚀 ${{ env.MESSAGE }}
            ||executed|failed|
            |--:|--:|--:|
            |requests|${{ env.result_Run_Stats_Requests_total }}|${{ env.result_Run_Stats_Requests_failed }}|
            |assertions|${{ env.result_Run_Stats_Assertions_total }}|${{ env.result_Run_Stats_Assertions_failed }}|
          repo-token: ${{ secrets.GITHUB_TOKEN }}
