name: Lint JSON

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    id: lint-json
    steps:
      - uses: actions/checkout@v2
      - name: lint-json
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"