name: Testes Integrados de API com Newman

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  # newman-test:
  #   uses: Vis-Rodrigues/workflow-template/.github/workflows/test-api-newman.yml@v2
  #   with:
  #     collection: treinamento-pipeline.postman_collection
  #     environment: environment-qa.postman_environment
  #     artifact_name: report

  # deploy-github-page:
  #   uses: Vis-Rodrigues/workflow-template/.github/workflows/deploy-github-page.yml@v2
  #   needs: [newman-test]
  #   with:
  #     artifact_download: report

  test-api:
    name: Testes de API com Newman
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Instalar node
      uses: actions/setup-node@v2
      with: 
        node-version: '14.x'
    
    - name: Instalar newman
      run: |
       npm install -g newman newman-reporter-htmlextra @decathlon/newman-reporter-pullrequest-decorator & \
       npm i newman-reporter-json-summary
    
    - name: Testes com Newman
      continue-on-error: true
      run: |
       mkdir -p report
       newman run treinamento-pipeline.postman_collection.json \
       -e environment-qa.postman_environment.json \
       -r cli,junit,json \
       -r htmlextra --reporter-htmlextra-export report/index.html \
       -r json-summary --reporter-summary-json-export output \
       -- color on \
       ${{ inputs.extra_options }}
    
    - name: Run API Tests
      id: run-newman
      continue-on-error: true
      uses: anthonyvscode/newman-action@v1
      with:
        collection: treinamento-pipeline.postman_collection.json
        environment: environment-qa.postman_environment.json
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Install comment PR
      if: github.event_name == 'pull_request'
      run: npm install -g @decathlon/newman-reporter-pullrequest-decorator

    - name: Newman report comment
      id: comment
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: |
        newman run treinamento-pipeline.postman_collection.json --environment=environment-qa.postman_environment.json -r @decathlon/pullrequest-decorator \
        --reporter-pullrequest-decorator-repo ${{ github.repository }} \
        --reporter-pullrequest-decorator-token ${{ secrets.GITHUB_TOKEN }} \
        --reporter-pullrequest-decorator-checkname vivi \
        --reporter-pullrequest-decorator-refcommit ${{ github.event.pull_request.head.sha }}


    - name: Newman report comment
      id: comment2
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: |
        newman run treinamento-pipeline.postman_collection.json --environment=environment-qa.postman_environment.json -r @decathlon/pullrequest-decorator \
        --reporter-export report/index2.html
    
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          Como vai? Estou bem graças a Deus!
          ${{ steps.run-newman.outputs.summary }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload relatório da execucao dos testes
      uses: actions/upload-artifact@v3
      with: 
       name: report
       path: report
       retention-days: 1

  github-page:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test-api

    steps:
      - uses: actions/checkout@v3
      - name: Download a Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: report
          path: report
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report
