name: Testes Integrados de API com Newman

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - comment2

env:
  COLLECTION: treinamento-pipeline.postman_collection.json
  ENVIRONMENT: environment-qa.postman_environment.json
  REPORT_JSON_PATH: report/result.json

jobs:

  # newman-test:
  #   uses: Vis-Rodrigues/workflow-template/.github/workflows/test-api-newman.yml@v2
  #   with:
  #     collection: treinamento-pipeline.postman_collection
  #     environment: environment-qa.postman_environment
  #     artifact_name: report

  # deploy-github-page:
  #   uses: Vis-Rodrigues/workflow-template/.github/workflows/deploy-github-page.yml@v2
  #   needs: [newman-test]
  #   with:
  #     artifact_download: report

  test-api:
    name: Testes de API com Newman
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Instalar node
      uses: actions/setup-node@v2
      with: 
        node-version: '14.x'
    
    - name: Instalar newman
      run: |
       npm install -g newman 
       npm install -g newman-reporter-htmlextra
       npm install -g newman-reporter-json-summary
    
    - name: Testes com Newman
      id: newman
      continue-on-error: true
      run: |
       mkdir -p report
       newman run ${{ env.COLLECTION }} \
       -e ${{ env.ENVIRONMENT }} \
       -r cli,json,htmlextra,json-summary \
       --reporter-htmlextra-export report/index.html \
       --reporter-htmlextra-logs \
       --reporter-htmlextra-showEnvironmentData \
       --reporter-htmlextra-timezone "America/Sao_Paulo" \
       --reporter-htmlextra-title ${{ github.event.repository.name }} \
       --reporter-htmlextra-browserTitle ${{ github.event.repository.name }} \
       --reporter-summary-json-export ${{ env.REPORT_JSON_PATH }}
       -- color on \
       ${{ inputs.extra_options }}
    
    - name: Upload relatório da execucao dos testes
      uses: actions/upload-artifact@v3
      with: 
       name: report
       path: report
       retention-days: 1

    # - name: Run API Tests
    #   id: run-newman
    #   continue-on-error: true
    #   uses: anthonyvscode/newman-action@v1
    #   with:
    #     collection: treinamento-pipeline.postman_collection.json
    #     environment: environment-qa.postman_environment.json
    #     reporters: cli

    # - id: data
    #   uses: gr2m/get-json-paths-action@v1.x
    #   with:
    #     json: ${{ steps.run-newman.outputs.summary }}
    #     total: "Run.Stats.Requests.total"
    
    # - name: show result 
    #   env:
    #     result: ${{ steps.data.outputs.json.Run.Stats.Requests.total }}"
    #   run: "echo Total ${{ steps.data.outputs.json.Run.Stats.Requests.total }}"

    - name: JSON to variables
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: ${{ env.REPORT_JSON_PATH }}
        prefix: result
        # masked: true
    
    - name: Show output
      run: echo "The time was ${{ env.result_Stats_Requests_total }}"

    - uses: mshick/add-pr-comment@v1
      if: github.event_name == 'pull_request'
      with:
        message: |
          ||executed|failed|
          |--|--|--|
          |requests|${{ env.result_Stats_Requests_total }}|${{ env.result_Stats_Requests_failed }}|
          |assertions|${{ env.result_Stats_Assertions_total }}|${{ env.result_Stats_Assertions_failed }}|
          "Total de requisições ${{ steps.data.outputs.total }}"
        repo-token: ${{ secrets.GITHUB_TOKEN }}



  # github-page:
  #   name: Deploy to GitHub Pages
  #   runs-on: ubuntu-latest
  #   needs: test-api

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download a Artifact
  #       uses: actions/download-artifact@v3.0.0
  #       with:
  #         name: report
  #         path: report
      
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: report
